Лабораторная работа №1

Ермаков ПИ22-3

In [183]:
## задание 1
import numpy as np
ing = np.loadtxt('/minutes_n_ingredients.csv', delimiter = ',', skiprows = 1, 
                dtype = {'names': ['id', 'minutes', 'n_ingredients'],
                         'formats' : ['int32', 'int32', 'int32']})
print(ing[:5])

[(127244, 60, 16) ( 23891, 25,  7) ( 94746, 10,  6) ( 67660,  5,  6)
 (157911, 60, 14)]


In [184]:
#задание 2
max_minutes = ing['minutes'].max()
max_n_ingredients = ing['n_ingredients'].max()
min_minutes = ing['minutes'].min()
min_n_ingredients = ing['n_ingredients'].min()
av_minutes = round(ing['minutes'].sum()/ing.shape[0], 2)
av_n_ingredients = ing['n_ingredients'].sum()/ing.shape[0]
med_minutes = np.median(ing['minutes'])
med_n_ingredients = np.median(ing['n_ingredients'])
print(f'Время: \n\tМаксимальное: {max_minutes} минут\n\tМинимальное: {min_minutes} минут\n\tСреднее: {av_minutes} минут\n\tМедиана: {med_minutes}')
print(f'Количество ингредиентов: \n\tМаксимальное: {max_n_ingredients}\n\tМинимальное: {min_n_ingredients}\n\tСреднее: {av_n_ingredients}\n\tМедиана: {med_n_ingredients}')

Время: 
	Максимальное: 2147483647 минут
	Минимальное: 0 минут
	Среднее: 21601.0 минут
	Медиана: 40.0
Количество ингредиентов: 
	Максимальное: 39
	Минимальное: 1
	Среднее: 9.05528
	Медиана: 9.0


In [185]:
## задание 3
q075 = np.quantile(ing['minutes'], 0.75)
ing['minutes'] = np.clip(ing['minutes'], 0, q075)
print('Значение времени ограничено квантилем 0,75',ing)

Значение времени ограничено квантилем 0,75 [(127244, 60, 16) ( 23891, 25,  7) ( 94746, 10,  6) ... (498432, 65, 15)
 (370915,  5,  4) ( 81993, 65, 14)]


In [186]:
##задание 4
num_zero = (ing['minutes'] == 0).sum()
ing['minutes'] = np.clip(ing['minutes'], 1, None)
print(f'Количество нулей: {num_zero}, все заменены на единицы')

Количество нулей: 479, все заменены на единицы


In [8]:
## задание 5
## уникальный рецепт - уникальный набор из времени и кол-ва ингредиентов
a = np.stack((ing['minutes'], ing['n_ingredients']), axis=1)
uniq = np.unique(a, axis=0)
print(f'Количесво уникальных рецептов: {uniq.shape[0]}')

Количесво уникальных рецептов: 1135


In [13]:
## задание 6
unique, counts = np.unique(ing['n_ingredients'], return_counts=True)
print('Все уникальные значения кол-ва ингредиентов и их количество:','\n', dict(zip(unique, counts)))

Все уникальные значения кол-ва ингредиентов и их количество: 
 {1: 13, 2: 926, 3: 2895, 4: 5515, 5: 7913, 6: 9376, 7: 10628, 8: 10951, 9: 10585, 10: 9591, 11: 8297, 12: 6605, 13: 4997, 14: 3663, 15: 2595, 16: 1767, 17: 1246, 18: 790, 19: 573, 20: 376, 21: 217, 22: 161, 23: 105, 24: 69, 25: 50, 26: 28, 27: 16, 28: 16, 29: 12, 30: 12, 31: 3, 32: 1, 33: 2, 34: 1, 35: 3, 37: 1, 39: 1}


In [15]:
## задание 7
cond = np.where(ing['n_ingredients'] <= 5)
ing_new = ing[cond]
print('Рецепты с кол-вом ингредиентов не более 5:', '\n', ing_new)

Рецепты с кол-вом ингредиентов не более 5: 
 [(446597, 15, 5) (204134,  5, 3) ( 25623,  6, 4) ... ( 52088, 60, 5)
 (128811, 15, 4) (370915,  5, 4)]


In [17]:
## задание 8
ing_per_min = ing['minutes']/ing['n_ingredients']
print('Максимальное количество ингредиентов в минуту:',ing_per_min.max())

Максимальное количество ингредиентов в минуту: 65.0


In [18]:
####задание 9
top = np.sort(ing, order = 'minutes')[::-1]
top = top['n_ingredients'][:100].sum()/100
print('Среднее количество ингредиентов в топ-100 по продолжительности рецептах:', top)

Среднее количество ингредиентов в топ-100 по продолжительности рецептах: 13.11


In [20]:
###задание 10
print('10 рандомных рецептов', '\n', ing[np.random.randint(0, ing.shape[0], size = 10)])

10 рандомных рецептов 
 [(347481,  5,  4) (228958,  5,  8) (220525, 65, 10) (175139, 55,  7)
 (415373, 25, 10) (391531, 15,  6) (302269, 65,  4) ( 33604, 65,  9)
 (  8370, 40,  9) (444672, 65, 14)]


In [30]:
###задание 11
less = np.where(ing['n_ingredients'] < av_n_ingredients)
percent = int(round(ing[less].shape[0] / ing.shape[0], 2)*100)
print(percent, '%')

59 %


In [111]:
## задание 12
cond1 = np.where(ing_new[:, 1] <= 20)
cond2 = np.where(ing_new[:, 2] <= 5)
ing_new = np.c_[ing['id'], ing['minutes']]
z_arr = np.zeros(100000)
ing_new = np.c_[ing_new, ing['n_ingredients']]
ing_new = np.c_[ing_new, z_arr].astype(int)
## сымитировал копию(3-6 строчки) чтобы избежать конфликта типов данных, 
## дальше определил столбики, подходящие
## под 1е, потом под 2е условия и соединил их
ing_new1 = ing_new.copy()
ing_new2 = ing_new.copy()
ing_new1[cond1, 3] = 1
ing_new2[cond2, 3] = 1
ing_new[:,3] = ing_new1[:, 3]*ing_new2[:, 3]
print(ing_new[:50])

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 [ 67660      5      6      0]
 [157911     60     14      0]
 [152828     40      7      0]
 [ 33941     18      9      0]
 [446597     15      5      1]
 [366174      7      9      0]
 [ 74205     20      7      0]
 [504666     65     20      0]
 [ 81006     12      7      0]
 [280968     65     11      0]
 [204134      5      3      1]
 [ 18593     35      7      0]
 [ 25623      6      4      1]
 [ 65559     24     14      0]
 [ 99836     65      7      0]
 [ 87775     65     13      0]
 [425704     40     12      0]
 [101799     10      8      0]
 [106325     65     11      0]
 [ 99283     65      6      0]
 [179504     65     11      0]
 [276123     60      7      0]
 [498382     65     18      0]
 [197140     40      6      0]
 [484223     18      4      1]
 [385472     65      9      0]
 [ 63150     65      4      0]
 [378114     20     11      0]
 [318295     65      7      0]
 [259784

In [94]:
## задание 13
print((ing_new[:, 3].sum()/ing.shape[0])*100, '%')

9.552 %


In [181]:
## задание 14
ing_cube = np.c_[ing_new, np.zeros(100000)].astype(int)
short = np.where(ing_cube[:, 1] <= 10)
long = np.where(ing_cube[:, 1] > 20)
ing_cube[short, 4] = 1
ing_cube[long, 4] = 3
ing_cube[np.where(ing_cube[:, 4] == 0), 4] = 2
# short = 1
# normal = 2
# long = 3
unique, counts = np.unique(ing_cube[:, 4], return_counts=True)
print(dict(zip(unique, counts)))
number = min(counts)
print(number)  #12466
# значит, будет куб 3*12466*3
cube_dim1 = ing_cube[np.where(ing_cube[:, 4] == 1), :3][0]
cube_dim2 = ing_cube[np.where(ing_cube[:, 4] == 2), :3][0]
cube_dim3 = ing_cube[np.where(ing_cube[:, 4] == 3), :3][0]
cube_dim1 = cube_dim1[:12466]
cube_dim2 = cube_dim2[:12466]
cube_dim3 = cube_dim3[:12466]
## разделил массивы по сложности, обрезал по самому короткому
cube = np.zeros((3, 12466, 3), dtype='int')
cube[0] = cube_dim1
cube[1] = cube_dim2
cube[2] = cube_dim3
print(cube)

{1: 12466, 2: 14184, 3: 73350}
12466
[[[ 94746     10      6]
  [ 67660      5      6]
  [366174      7      9]
  ...
  [420725      5      3]
  [  4747      0      9]
  [370915      5      4]]

 [[ 33941     18      9]
  [446597     15      5]
  [ 74205     20      7]
  ...
  [230115     20      7]
  [496131     20      9]
  [365818     20      6]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [ 68428     65     10]
  [312995     65      7]
  [ 93651     65     12]]]
